pyNative NumPy examples

In [ ]:
import numpy as np 

In [32]:
#Exercise 1: Create a 4X2 integer array and Prints its attributes

l1 = [2,3,6,5,8,7,0,8]
arr = np.array(l1)
arr = arr.reshape(4,2)
arr = np.array(arr, dtype = 'int16')

print(arr)
print('Array shape is: ', arr.shape)
print('Array dimensions are: ', arr.ndim)
print('Length of each element of array in bytes: ', arr.itemsize)

[[2 3]
 [6 5]
 [8 7]
 [0 8]]
Array shape is:  (4, 2)
Array dimensions are:  2
Length of each element of array in bytes:  2


In [ ]:
#Exercise 2: Create a 5X2 integer array from a range between 100 to 200 
# such that the difference between each element is 10

arr1 = np.arange(100,200,10).reshape(5,2)

print(arr1)


[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [72]:
#Exercise 3: Following is the provided numPy array. Return array of items
#  by taking the third column from all rows

sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
print('3-th column elements: ')
sampleArray = sampleArray[...,2]
print(sampleArray)


[[11 22 33]
 [44 55 66]
 [77 88 99]]
3-th column elements: 
[33 66 99]


In [82]:
#Exercise 4: Return array of odd rows and even columns from below numpy array

sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)

print("\n new arraw which consisting of odd rows and even columns: ")
arr2 = sampleArray[::2, 1::2]
print(arr2)



[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 new arraw which consisting of odd rows and even columns: 
[[ 6 12]
 [30 36]
 [54 60]]


In [85]:
# Exercise 5: Create a result array by adding the following two NumPy arrays. 
# Next, modify the result array by calculating the square of each element

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
newArr = arrayOne+ arrayTwo
print('Addition of 2 arrays is:')
print(newArr)
print('Kvadrati:')
resArr = newArr**2
print(resArr)



Addition of 2 arrays is:
[[20 39 33]
 [25 25 28]]
Kvadrati:
[[ 400 1521 1089]
 [ 625  625  784]]


In [92]:
#Exercise 6: Split the array into four equal-sized sub-arrays
arr3 = np.arange(10,34,1).reshape(8,3)
print(arr3)
print()
arr4 = np.split(arr3,4)
print(arr4)





[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]
